POST http://localhost:5050/artist/register HTTP/1.1
Content-Type: application/json

{
"email": "eelst@gmail.com",
"password": "solimano",
"name": "Elio e le Storie Tese",
"members": "5",
"region": "Liguria",
"city": "Genova",
"address": "Via Arno 19",
"genre": ["rock", "demenziale", "progressive", "progressive-metal"],
"instruments": ["guitar", "piano", "arp", "violin"],
"description" : "Elio e le Storie Tese (talvolta abbreviato in EelST o Elii) è un gruppo musicale italiano di Milano, fondato da Stefano Elio Belisari nel 1980",
"lat": "44.4492",
"lon": "8.8807",
"instagram" : "www.instagram.com",
"facebook" : "www.facebook.com",
"webSite" : "www.google.com",
"proPic" : "https://www.rollingstone.it/wp-content/uploads/2020/07/elio-e-le-storie-tese.jpg"
}

#####
PATCH http://localhost:5050/artist/64f9db7941f2a0fb64357885/validate HTTP/1.1
Content-Type: application/json

#####
GET http://localhost:5050/artist/filter?name=gesu

#####
GET http://localhost:5050/artist/filter?genre=rock,MEtal,jazz&instruments=violin,PIANO&name=leprous&members=4&region=lombardia&city=rho&lat=45.5489856&lon=9.1608651&distance=9