POST http://localhost:5050/event/newEvent HTTP/1.1
Content-Type: application/json

{
    "location" : "64fc7b2d4534c8c1383734d8",
    "name" : "Cavalli",
    "description" : "Una serata in compagnia della musica da balera",
    "genres" : ["liscio", "waltzer"],
    "requiredArtist" : "Band",
    "refund" : "Non sono previsti rimborsi spesa",
    "benefits" : "Cena e consumazione incluse",
    "duration" : "2h",
    "date" : "14/04"
}

#####
GET http://localhost:5050/event/artistCandidature/65006a399046ad91e5e54642

#####
POST http://localhost:5050/event/candidate?id=650049d934a673c950550f52&artistId=65006a399046ad91e5e54642 HTTP/1.1
Content-Type: application/json

{
    "cachet" : "300€",
    "note" : "Nessuna"
}

#####
GET http://localhost:5050/event/removeCandidature/65049060d0a45010c354f10c/65006a399046ad91e5e54642
